services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundleConfig: '%shapecode_subscription.config%'

    # trader
    Shapecode\SubscriptionBundle\Command\:
        resource: '../../Command/*'

    Shapecode\SubscriptionBundle\Feature\:
        resource: '../../Feature/*'

    Shapecode\SubscriptionBundle\Listener\:
        resource: '../../Listener/*'

    Shapecode\SubscriptionBundle\Strategy\:
        resource: '../../Strategy/*'

    Shapecode\SubscriptionBundle\Subscription\:
        resource: '../../Subscription/*'

    Shapecode\SubscriptionBundle\Twig\:
        resource: '../../Twig/*'
