services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $config: '%shapecode_subscription.config%'

    # trader
    Shapecode\SubscriptionBundle\Command\:
        resource: '../src/Command/*'

    Shapecode\SubscriptionBundle\Subscription\:
        resource: '../src/Subscription/*'

    Shapecode\SubscriptionBundle\Strategy\:
        resource: '../src/Strategy/*'
